import 'package:ecommerce_app/src/features/products/domain/product.dart';

/// Test products to be used until a data source is implemented
const kTestProducts = [
  Product(
    id: '1',
    imageUrl: 'assets/products/product1.jpg',
    title: 'Bruschetta plate',
    description: 'Lorem ipsum',
    price: 15,
    availableQuantity: 5,
    avgRating: 4.5,
    numRatings: 2,
  ),
  Product(
    id: '2',
    imageUrl: 'assets/products/product2.jpg',
    title: 'Mozzarella plate',
    description: 'Lorem ipsum',
    price: 13,
    availableQuantity: 5,
    avgRating: 4,
    numRatings: 2,
  ),
  Product(
    id: '3',
    imageUrl: 'assets/products/product3.jpg',
    title: 'Pasta plate',
    description: 'Lorem ipsum',
    price: 17,
    availableQuantity: 5,
    avgRating: 5,
    numRatings: 2,
  ),
  Product(
    id: '4',
    imageUrl: 'assets/products/product4.jpg',
    title: 'Piggy Bank Blue',
    description: 'Lorem ipsum',
    price: 12,
    availableQuantity: 5,
  ),
  Product(
    id: '5',
    imageUrl: 'assets/products/product5.jpg',
    title: 'Piggy Bank Green',
    description: 'Lorem ipsum',
    price: 12,
    availableQuantity: 10,
  ),
  Product(
    id: '6',
    imageUrl: 'assets/products/product6.jpg',
    title: 'Piggy Bank Pink',
    description: 'Lorem ipsum',
    price: 12,
    availableQuantity: 10,
  ),
  Product(
    id: '7',
    imageUrl: 'assets/products/product7.jpg',
    title: 'Pizza plate',
    description: 'Lorem ipsum',
    price: 18,
    availableQuantity: 10,
    avgRating: 4.7,
    numRatings: 10,
  ),
  Product(
    id: '8',
    imageUrl: 'assets/products/product8.jpg',
    title: 'Plate and Bowl',
    description: 'Lorem ipsum',
    price: 21,
    availableQuantity: 10,
    avgRating: 4.1,
    numRatings: 12,
  ),
  Product(
    id: '9',
    imageUrl: 'assets/products/product9.jpg',
    title: 'Salt and pepper lemon',
    description: 'Lorem ipsum',
    price: 11,
    availableQuantity: 10,
  ),
  Product(
    id: '10',
    imageUrl: 'assets/products/product10.jpg',
    title: 'Salt and pepper olives',
    description: 'Lorem ipsum',
    price: 11,
    availableQuantity: 10,
  ),
  Product(
    id: '11',
    imageUrl: 'assets/products/product11.jpg',
    title: 'Snacks plate',
    description: 'Lorem ipsum',
    price: 24,
    availableQuantity: 10,
  ),
  Product(
    id: '12',
    imageUrl: 'assets/products/product12.jpg',
    title: 'Flowers plate',
    description: 'Lorem ipsum',
    price: 22,
    availableQuantity: 10,
  ),
  Product(
    id: '13',
    imageUrl: 'assets/products/product13.jpg',
    title: 'Juicer for citrus fruits',
    description: 'Lorem ipsum',
    price: 14,
    availableQuantity: 10,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/products/product14.jpg',
    title: 'Honey pot',
    description: 'Lorem ipsum',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/products/product15.jpg',
    title: 'Honey pot',
    description: 'Lorem ipsum',
    price: 16,
    availableQuantity: 10,
  ),
];
